/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { Santa } from "../../../assets";

export function Player(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(Santa);
  const { actions } = useAnimations(animations, group);
  console.log(actions);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="Santa_Armature"
          position={[-1.876, -1.371, 4.503]}
          rotation={[1.544, -0.019, 0.002]}
        >
          <skinnedMesh
            name="Santa"
            geometry={nodes.Santa.geometry}
            material={materials.Santa_texture}
            skeleton={nodes.Santa.skeleton}
          />
          <primitive object={nodes.Root} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(Santa);
